export const FAKEDATA = {
  decks: [
    {
      deck_data: {
        background_color: 4210752.0,
        on: true,
        grid_y: 10.0,
        snap_grid: 1.0,
        lb_version: '2025.1.1',
        background_image: '',
        sammi_version: '2025.1.1',
        encrypted: false,
        adaptive_resizing: 1.0,
        unique_id: '20250423233851786754755',
        button_list: [
          {
            color: 12632256.0,
            persistent: 1.0,
            text: '',
            release_duration: 0.0,
            queueable: 0.0,
            command_list: [
              {
                b1: 'all',
                cmd: 66.0,
                obsid: 'Main',
                pos: 0.0,
                vis: 1.0,
                ms: 0.0,
                sel: 0.0,
                dis: 0.0,
                xpan: 0.0,
                b0: 'blendshapes',
              },
            ],
            press_type: 0.0,
            x: 0.0,
            is_transparent: 0.0,
            border: 2.0,
            image: '',
            triggers: [
              {
                case_sensitive: 0.0,
                message: '*',
                group_id: '',
                button_id: 'ID4',
                trg: 26.0,
                allow_empty_wildcard: 0.0,
              },
              {
                case_sensitive: 0.0,
                message: '*',
                group_id: '',
                button_id: 'ID4',
                trg: 12.0,
                allow_empty_wildcard: 0.0,
              },
            ],
            group_id: '',
            overlappable: 0.0,
            init_variable: '',
            deck: 5.0,
            width: 0.20000000000000001110223024625157,
            button_id: 'ID4',
            button_duration: 0.0,
            y: 0.0,
            switch_deck: '',
            height: 0.20000000000000001110223024625157,
            release_list: [],
            functions: 81.0,
            stretch: 0.0,
          },
          {
            color: 12589847.0,
            persistent: 1.0,
            text: 'test',
            release_duration: 0.0,
            queueable: 0.0,
            command_list: [
              {
                b1: '',
                cmd: 148.0,
                obsid: 'Main',
                pos: 0.0,
                vis: 1.0,
                ms: 0.0,
                sel: 0.0,
                dis: 0.0,
                xpan: 0.0,
                b0: 'HI this is a message',
              },
            ],
            press_type: 0.0,
            x: 0.40000000000000002220446049250313,
            is_transparent: 0.0,
            border: 2.0,
            image: '',
            triggers: [
              {
                sub: 0.0,
                user_name: '',
                case_sensitive: 0.0,
                founder: 0.0,
                message: 'test',
                moderator: 0.0,
                group_id: '',
                vip: 0.0,
                button_id: 'ID5',
                broadcaster: 0.0,
                trg: 0.0,
                allow_empty_wildcard: 0.0,
              },
            ],
            group_id: '',
            overlappable: 0.0,
            init_variable: '',
            deck: 5.0,
            width: 0.19999999999999995559107901499374,
            button_id: 'ID5',
            button_duration: 0.0,
            y: 0.10000000000000000555111512312578,
            switch_deck: '',
            height: 0.19999999999999998334665463062265,
            release_list: [],
            functions: 81.0,
            stretch: 0.0,
          },
        ],
        deck_name: 'Deck 2',
        grid_x: 10.0,
        stretch: 0.0,
      },
      unique_id: '20250423233851786754755',
      include_image: {},
    },
    {
      deck_data: {
        background_color: 4210752.0,
        on: true,
        grid_y: 2.0,
        snap_grid: true,
        lb_version: '2025.3.1',
        background_image: '',
        sammi_version: '2025.3.1',
        adaptive_resizing: true,
        unique_id: '20251118182554562761953',
        button_list: [
          {
            color: 12632256.0,
            persistent: true,
            text: '!laugh\\n',
            release_duration: 0.0,
            queueable: false,
            command_list: [
              {
                b1: '',
                cmd: 148.0,
                obsid: 'Main',
                pos: 0.0,
                vis: true,
                ms: 0.0,
                sel: false,
                dis: false,
                xpan: 0.0,
                b0: 'hahahahaha!',
              },
            ],
            press_type: 0.0,
            x: 0.0,
            is_transparent: false,
            border: 2.0,
            image: '',
            triggers: [
              {
                sub: false,
                user_name: '',
                case_sensitive: false,
                founder: false,
                message: '!laugh',
                moderator: false,
                group_id: '',
                vip: false,
                button_id: 'ID6',
                broadcaster: false,
                trg: 0.0,
                allow_empty_wildcard: false,
              },
            ],
            group_id: '',
            overlappable: false,
            init_variable: '',
            deck: 7.0,
            width: 0.5,
            button_id: 'ID6',
            button_duration: 0.0,
            y: 0.0,
            switch_deck: '',
            height: 0.5,
            release_list: [],
            functions: 81.0,
            stretch: false,
          },
          {
            color: 12632256.0,
            persistent: true,
            text: '!fart',
            release_duration: 0.0,
            queueable: false,
            command_list: [
              {
                b1: '',
                cmd: 2.0,
                obsid: 'Main',
                pos: 0.0,
                vis: true,
                ms: 0.0,
                sel: false,
                dis: false,
                xpan: 0.0,
                b0: '',
                v0: 0.29999999999999998889776975374843,
              },
            ],
            press_type: 0.0,
            x: 0.5,
            is_transparent: false,
            border: 2.0,
            image: '',
            triggers: [
              {
                sub: false,
                user_name: '',
                case_sensitive: false,
                founder: false,
                message: '!laugh',
                moderator: false,
                group_id: '',
                vip: false,
                button_id: 'ID7',
                broadcaster: false,
                trg: 0.0,
                allow_empty_wildcard: false,
              },
            ],
            group_id: '',
            overlappable: false,
            init_variable: '',
            deck: 7.0,
            width: 0.5,
            button_id: 'ID7',
            button_duration: 0.0,
            y: 0.0,
            switch_deck: '',
            height: 0.5,
            release_list: [],
            functions: 83.0,
            stretch: false,
          },
        ],
        deck_name: 'Deck 3',
        grid_x: 2.0,
        stretch: false,
      },
      unique_id: '20251118182554562761953',
      include_image: {},
    },
  ]
};
